version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn venuemaster.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - env.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: venuemaster_prod
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword

volumes:
  static_volume:
  media_volume:
