#!/usr/bin/env bash
set -e

until pg_isready -U "$POSTGRES_USER" --host "$POSTGRES_HOST"; do
  echo $POSTGRES_USER
  echo $POSTGRES_HOST
  >&2 echo "Postgres is unavailable - sleeping for 10"
  sleep 10
done

./manage.py runserver 0.0.0.0:8000