#!/usr/bin/env bash
set -e

docker-compose build > /dev/null
docker-compose up --remove-orphans -d
docker-compose stop web
docker-compose run --rm --service-ports web

docker-compose run --rm --no-deps web ./manage.py migrate
docker-compose run --rm --no-deps --service-ports --name web web "${@:1}"
